name: Build

on:
  push:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    name: generate node matrix
    outputs:
      all-nodes: ${{ steps.nodes.outputs.all-nodes }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: nodes
        run: |
          echo "all-nodes=$(nix eval .#colmena --no-substitute --apply 'with builtins; x: filter (f: !elem f [ "defaults" "meta" ]) (attrNames x)' --json)" >> $GITHUB_OUTPUT
  gen-matrix-hm:
    runs-on: ubuntu-latest
    name: generate hm matrix
    outputs:
      users: ${{ steps.users.outputs.users }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: users
        run: |
          echo "users=$(nix eval .#homeConfigurations --no-substitute --apply 'with builtins; x: (attrNames x)' --json)" >> $GITHUB_OUTPUT
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix flake check
  build:
    runs-on: ubuntu-latest
    name: build offline
    needs: 
      - gen-matrix
    strategy:
      matrix: 
        node: ${{ fromJson(needs.gen-matrix.outputs.all-nodes) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux i686-linux
      - uses: cachix/cachix-action@v14
        with:
          name: ryo
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build ${{ matrix.node }}
        run: >
          nix run nixpkgs#colmena --
          build -v
          --no-build-on-target
          --on ${{ matrix.node }}
  build-hm:
    runs-on: ubuntu-latest
    name: build home manager
    needs: 
      - check
      - gen-matrix-hm
    strategy:
      matrix: 
        user: ${{ fromJson(needs.gen-matrix-hm.outputs.users) }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v14
        with:
          name: ryo
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build home manager
        run: >
          nix run nixpkgs#home-manager --
          build -v
          --flake .#${{ matrix.user }}
