name: Build
on:
  push:
  workflow_call:

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    name: generate node matrix
    outputs:
      alive-nodes: ${{ steps.alive-matrix.outputs.alive-nodes }}
      offline-nodes: ${{ steps.offline-matrix.outputs.offline-nodes }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - id: nodes
        run: |
          echo "nodes=$(nix eval .#colmena --no-substitute --apply 'with builtins; x: filter (f: !elem f [ "defaults" "meta" ]) (attrNames x)' --json)" >> $GITHUB_OUTPUT
      - id: alive-nodes
        run: echo "alive=$(tailscale status --json | nix run nixpkgs#jq -- -c '[.Peer | to_entries[] | select(.value.Online == true) | .value.HostName]')" >> $GITHUB_OUTPUT
      - id: alive-matrix
        run: echo "alive-nodes=$(nix run nixpkgs#jq -- -cn --argjson nodes '${{ steps.nodes.outputs.nodes }}' --argjson alive '${{ steps.alive-nodes.outputs.alive }}' '$nodes - ($nodes - $alive)')" >> $GITHUB_OUTPUT
      - id: offline-matrix
        run: echo "offline-nodes=$(nix run nixpkgs#jq -- -cn --argjson nodes '${{ steps.nodes.outputs.nodes }}' --argjson alive '${{ steps.alive-nodes.outputs.alive }}' '$nodes - $alive')" >> $GITHUB_OUTPUT
  gen-matrix-hm:
    runs-on: ubuntu-latest
    name: generate hm matrix
    outputs:
      users: ${{ steps.users.outputs.users }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: users
        run: |
          echo "users=$(nix eval .#homeConfigurations --no-substitute --apply 'with builtins; x: (attrNames x)' --json)" >> $GITHUB_OUTPUT
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
  apply-online:
    runs-on: ubuntu-latest
    name: apply online
    needs: 
      - gen-matrix
      - check
    strategy:
      fail-fast: false
      matrix: 
        node: ${{ fromJson(needs.gen-matrix.outputs.alive-nodes) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux i686-linux
      - uses: cachix/cachix-action@v14
        with:
          name: ryo
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Configure GPG
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: build ${{ matrix.node }}
        run: >
          nix run nixpkgs#colmena --
          apply -v
          --no-build-on-target
          --on ${{ matrix.node }}
  build-offline:
    runs-on: ubuntu-latest
    name: build offline
    needs: 
      - gen-matrix
      - check
    strategy:
      matrix: 
        node: ${{ fromJson(needs.gen-matrix.outputs.offline-nodes) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux i686-linux
      - uses: cachix/cachix-action@v14
        with:
          name: ryo
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build ${{ matrix.node }}
        run: >
          nix run nixpkgs#colmena --
          build -v
          --no-build-on-target
          --on ${{ matrix.node }}
  build-hm:
    runs-on: ubuntu-latest
    name: build home manager
    needs: 
      - check
      - gen-matrix-hm
    strategy:
      matrix: 
        user: ${{ fromJson(needs.gen-matrix-hm.outputs.users) }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v14
        with:
          name: ryo
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build home manager
        run: >
          nix run nixpkgs#home-manager --
          build -v
          --flake .#${{ matrix.user }}
