name: Build
on:
  push:
  workflow_call:

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    name: generate node matrix
    outputs:
       matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: gen-matrix
        name: generate matrix list
        run: >
          echo "matrix=$(
          nix eval .#colmena 
          --no-substitute
          --apply
          'with builtins; x: filter (f: !elem f [ "defaults" "meta" ]) (attrNames x)'
          --json
          )" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    name: build system
    needs: gen-matrix
    strategy:
      matrix: 
        node: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: build ${{ matrix.node }}
        run: >
          nix run nixpkgs#colmena --
          build -v
          --no-build-on-target
          --on ${{ matrix.node }}

